### PR TITLE
Logo

### LINKED ISSUE #187: Logo for python-semver
As discussed in https://github.com/python-semver/python-semver/issues/177#issuecomment-549307654 a logo for python-semver is required.

Logo should be visible in https://github.com/python-semver/ and be [our visual identity in documentation](https://github.com/python-semver/python-semver/pull/185#issuecomment-552177934).

### PR DESCRIPTION
**Pull request by tomschr**
This PR contains:

* Logo (squared logo) in SVG format
* Configuration option `html_logo` in `docs/conf.py`

Co-authored-by: scls19fr

Closes #187

### CODE REVIEW

**Comment by scls19fr** [comment]
Maybe you should add a note in CHANGELOG also.

**Comment by tomschr** [comment]
Oh yes, of course! I've added a line in commit 63d4d22

**Comment by scls19fr** [comment]
I can't understand what's wrong with that PR.

Some checks haven’t completed yet
2 expected and 1 successful checks
Travis CI - Branch Expected — Waiting for status to be reported
Required
continuous-integration/travis-ci Expected — Waiting for status to be reported
Required

I tried triggering Travis. But it doesn't help.

**Comment by tomschr** [comment]
Hmn, strange. I've looked at Travis and it looks ok. There was also no incidents reported on status.github.com... :thinking: :thought_balloon:

**Comment by scls19fr** [comment]
Hi @tomschr,
I've retriggered Travis this morning... but it had no effects.
I see no other solution than closing this PR and opening an other one.
Really sorry about that.

**Comment by tomschr** [comment]
@scls19fr Don't worry such things can happen. :smile: Had this strange behavior in the past too from time to time.
I'm not aware that I did something wrong, the only change was the logo and the Changelog. :wink: 

If I should open another PR to help you, let me know. :-)

**Comment by scls19fr** [comment]
@tomschr Could you work on a `feature/logo3` PR? With such a number it will be synchronized with our logo 😄

**Comment by tomschr** [comment]
@scls19fr Sure, no problem. I've created PR #189 and closing this

> With such a number it will be synchronized with our logo :smile: 

Indeed. :smile:

**Pull request closed without merging**
