### PR TITLE
Move to GH org

### PR DESCRIPTION
**Pull request by scls19fr**
Related #177

### CODE REVIEW

**Comment by scls19fr** [comment]
CI builds are now available at
https://travis-ci.com/python-semver/python-semver

@tomschr could you tell me if I miss a link to fix?

**Comment by scls19fr** [comment]
I've just added this to CHANGELOG to keep a track.

**Comment by tomschr** [comment]
Good idea with the CHANGELOG, I didn't think of that. :wink: However, I would suggest a more prominent place, maybe somewhere in the README? Something like that:

```rst
.. note::

   With version 2.9.0, we changed the GitHub project. The project is now
   located under a separate domain ``python-semver``. Use the complete
   URL::

      https://github.com/python-semver/python-semver

   If you still have an old repository, correct your upstream URL to the new URL::

       git remote set-url upstream git@github.com:python-semver/python-semver.git
```

**Comment by scls19fr** [comment]
ok I let you create a PR to add this to doc because I don't know exactly where you prefer it to be.

**Comment by tomschr** [comment]
Sure, no problem. :+1: Thanks for merging.

**Comment by tomschr** [comment]
>  I don't know exactly where you prefer it to be.

I will open a pull request especially for you. :wink:

**Pull request merged**
