### PR TITLE
Describe Pydantic and semver in "Advanced topics"

### PR DESCRIPTION
**Pull request by tomschr**
This PR adds a new section into "Advanced topic". Fixing #343.

@calebstewart would you mind having a look? Anything that is missing, wrong, or could be done better? Would be really helpful. Thank you very much! :heart:

### CODE REVIEW

**Comment by tomschr** [comment]
If you don't object, I will merge it to master tomorrow. :slightly_smiling_face:

**Comment by calebstewart** [comment]
I just double checked the code. My only note is that the `__get_validators__` method should be `yield cls.parse` instead of `yield cls.pars`. Just a missing `e`.

Aside from that, the examples work, and make sense to me! Thanks for checking in with me! I appreciate it!

**Comment by tomschr** [comment]
> I just double checked the code. My only note is that the `__get_validators__` method should be `yield cls.parse` instead of `yield cls.pars`. Just a missing `e`.

Ahh, good catch! :+1:  Thanks for the hint, I've already fixed it.

> Aside from that, the examples work, and make sense to me! Thanks for checking in with me! I appreciate it!

Thank you! I've added you as a co-author. :slightly_smiling_face:

**Comment by tomschr** [comment]
The documentation is now available at https://python-semver.readthedocs.io/en/latest/advanced/combine-pydantic-and-semver.html

**Pull request merged**
