### PR TITLE
First attempt to create a logo for python-semver

### PR DESCRIPTION
**Pull request by tomschr**
This PR is the first attempt to create a logo for this project (mentioned in issue #177).

* Can be used as logo for this project and the documentation (that's the primary reason).
* Created it in Inkscape to have a resolution independent source. 
* Simplified and optimized the SVG XML a bit. 

It's quite simple, nothing spectacular. :wink: 

logo

The logo requires the Roboto font.

---

### Questions

1. Should we use something like this?
1. Should we place the `logo.svg` in the `docs` folder?
1. Any idea how to improve it?

Let me know if I should change it in any way.

### CODE REVIEW

**Comment by scls19fr** [comment]
Given that python-semver is a python library I would imagine a reference to a snake...
maybe with parts of semver on its tail...
Depending the size of tail, semver could even have prerelease and build part.

I will use 3 for major as it's current major number for Python... and will be soon major version number for python-semver

I would use x and y for minor and patch to show that's not current python-semver version and would add prerelease part and build part just for fun (build 42 because that's a geek number [42](https://en.wikipedia.org/wiki/Phrases_from_The_Hitchhiker%27s_Guide_to_the_Galaxy#Answer_to_the_Ultimate_Question_of_Life,_the_Universe,_and_Everything_(42)) and `rc.1` because we are humble enough to consider our organization as not totally finished and that it needs others / users opinion before being a "release".

So a semver like `3.x.y-rc.1+build.42'`

But I've unfortunately no artistic skills.

**Comment by tomschr** [comment]
Thanks for your ideas! :+1: 

> Given that python-semver is a python library I would imagine a reference to a snake...

Yes, I can do that, but aren't snakes not a bit... overused? :wink: 

> [...]

I agree most with your ideas. :wink: The only concern that I have is that the `3.x.y-rc.1+build.42` is probably a bit long for the logo. You need a condensed font or reduce the font size to make it fit into the rectangle. That could reduce legibility of the text. But I need to try it out.


> But I've unfortunately no artistic skills.

I have also very limited skills. :cry:  Give me some time, maybe I can conjure something better. :smile:

**Comment by tomschr** [comment]
Well, I've included the Python snakes and what you suggested... I'm not that convinced, but see yourself:

logo

**Comment by scls19fr** [comment]
Nice! let's use it!

**Comment by scls19fr** [comment]
Github needs squared picture for profile picture.
I just changed height of png file. So frameborder is rectangle but picture is square.

https://github.com/python-semver

**Comment by tomschr** [comment]
> Github needs squared picture for profile picture.

Oh I see. I can also create a squared version of this file if that fits a bit better.


> I just changed height of png file. So frameborder is rectangle but picture is square.

Ahh, nice!

I changed the width and height of the SVG so that becomes a squared picture. Furthermore, I've moved the text "semver" a bit below the Python snakes. Here is the result:

logo

**Comment by scls19fr** [comment]
I was wondering if Python logo shouldn't be before semver... like in our name python-semver... so it will be a kind of [rebus](https://en.wikipedia.org/wiki/Rebus)

**Comment by tomschr** [comment]
> I was wondering if Python logo shouldn't be before semver... like in our name python-semver... so it will be a kind of [rebus](https://en.wikipedia.org/wiki/Rebus)

You mean move the logo to the left? Actually that design was on purpose. :wink:

The reason for that is, the eye of the blue snake looks to the left. That means, it needs enough space. You could also interpret it as Python is looking at semver. :wink:  It maybe not "before", but it comes first and can be read from top to bottom.

If you move the two snakes to the left, the blue snake doesn't have any space left; it looks actually to a wall (the left side of the square). That may give a very strange interpretation...

I know this sounds a bit weird at a first glance. However, I got that idea from people photography and adapted it into this design.
Have you seen some photos from people? A professional photographer usually leaves spaces between the eyes of a person and the edge of the image. In almost all cases, they never place a person which is looking to an edge unless the photographer want to express a constriction.

Does that make sense to you? :wink:  (It's a bit hard to explain, but I hope it gives you an idea.)

**Comment by scls19fr** [comment]
It makes perfectly sense. Logo updated.
Thanks again.
So I think we can close.
Good night @tomschr

**Comment by tomschr** [comment]
@scls19fr Good morning. :wave: I forgot to ask:

1. Should we include the logo also into our documentation?
1. If yes, should I move the logo file into the `docs` folder?

It's a one-liner in `docs/conf.py`. Until we find a better logo, users can recognize it as our brand.

**Comment by scls19fr** [comment]
Hi @tomschr 
Yes it will nice to also have logo available in documentation

**Comment by scls19fr** [comment]
Sorry I didn't noticed that I closed this PR. Sorry.

**Comment by scls19fr** [comment]
Closes #187

**Comment by tomschr** [comment]
Don't worry, no problem. :-) 

Hmn, strange, I've pushed another commit, but it doesn't appear in this PR. Any idea?

**Comment by scls19fr** [comment]
I only see that I can't reopen this PR. Reopen and comment button is disabled and I see tooltip "The feature/logo branch was forced pushed or recreated"

I've just created an issue specifically about logo #187

**Comment by tomschr** [comment]
Oh I see, same here. :wink: Ok, I will create another branch and try it again. :-)

**Comment by tomschr** [comment]
Created new PR #188

**Comment by scls19fr** [comment]
Supersed by #187

**Pull request closed without merging**
