### PR TITLE
Fix #187: Create a squared logo

### LINKED ISSUE #187: Logo for python-semver
As discussed in https://github.com/python-semver/python-semver/issues/177#issuecomment-549307654 a logo for python-semver is required.

Logo should be visible in https://github.com/python-semver/ and be [our visual identity in documentation](https://github.com/python-semver/python-semver/pull/185#issuecomment-552177934).

### PR DESCRIPTION
**Pull request by tomschr**
Supersede PR #188 
Contains the following changes:

* Mentioned in issue #177
* Add logo to documentation
* Update CHANGELOG

Co-Authored-By: scls19fr

### CODE REVIEW

**Comment by scls19fr** [comment]
Squash and merge is disabled (again! :persevere:)

**Comment by tomschr** [comment]
I've looked into the Settings > Webhooks page for this repo and compared it with another repo which also uses Travis.  The events for this and the other repo are the same, both have the same events activated.

**Comment by ppkt** [comment]
@tomschr @scls19fr I'm not sure but it looks like something has changed in Travis recently, maybe we should update our workflow? https://github.com/travis-ci/travis-ci/issues/10204

**Comment by tomschr** [comment]
@ppkt Thank you very much for the hint! :+1: I would have never found that! :laughing: 

I've disabled now the "continuous-integration/travis-ci"  item, but left the other two intact. Let's see if this is working.

**Comment by tomschr** [comment]
Ok, seems the "Travis CI - Branch" is stalled, so I've disabled that too. Pushed another commit, this should work hopefully.

**Comment by tomschr** [comment]
@scls19fr It worked! Would you like to have a final look and merge it? Thanks! :+1:

**Comment by scls19fr** [comment]
Thanks @ppkt and @tomschr 
I'd have never found that without your help @ppkt!

**Comment by scls19fr** [comment]
Doc is available on https://python-semver.readthedocs.io/en/latest/

opinion?

I'm a bit skeptic about blue snake on blue background

**Comment by scls19fr** [comment]
Maybe we should remove alpha layer and have a white background for logo (and not transparent).
An other proposition could be to change RTD background

**Comment by tomschr** [comment]
Arghhh, I think that's a bit too heavy. :open_mouth:  Maybe we should reduce the size and---as @scls19fr suggested---add a white background.

Do you know if Sphinx has an option to customize the logo size? Otherwise I would suggest to convert the SVG logo into PNG for a specific size.

> An other proposition could be to change RTD background

You mean another theme?

**Comment by scls19fr** [comment]
Changing logo size and its background is probably simpler.

I don't know what is behiavor of RTD with smarphone... just wondering if vector graphics isn't better to support several resolution.

Changing RTD theme is probably overkilled

**Comment by tomschr** [comment]
I've opened now PR #190 for this.

**Comment by tomschr** [comment]
> I don't know what is behiavor of RTD with smarphone... just wondering if vector graphics isn't better to support several resolution.

Oh, I missed that part. Well, nowadays most modern browsers should cope with SVGs. I've tested it with Firefox 68.2.0 on Android 10 and the logo is displayed.

**Pull request merged**
