### PR TITLE
Create 3.0.0-dev.2

### PR DESCRIPTION
**Pull request by tomschr**
This PR contains:

* Build changelog from news files

----

However, trying to upload it to TestPyPI gives me the following error:

```
$ twine-3.6 --version
twine version 1.13.0 (pkginfo: 1.4.2, requests: 2.22.0, setuptools: 40.5.0,
requests-toolbelt: 0.9.1, tqdm: 4.31.1)

$ tox -e prepare-dist
[...]
prepare-dist run-test: commands[1] | twine check 'dist/*'
Checking dist/semver-3.0.0.dev2-py3-none-any.whl: PASSED
Checking dist/semver-3.0.0.dev2.tar.gz: PASSED

$ twine-3.6 upload --repository testpypi dist/* 
Uploading distributions to https://test.pypi.org/legacy/
Uploading semver-3.0.0.dev2-py3-none-any.whl
100%|█████████████████████████████████████████████| 24.2k/24.2k [00:01<00:00, 14.3kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 400 Client Error: 'attr: semver.__about__.__author_email__' is an invalid value for
Author-email.
Error: Use a valid email address See https://packaging.python.org/specifications/core-metadata
for more information. for url: https://test.pypi.org/legacy/
```

I also tried it with latest twine (version 3.2.0) without success.

@tlaferriere Thomas, do you know how this can be solved? Seems twine or (Test)PyPI doesn't understand our new `setup.cfg`. :cry:  Seems this is not really supported... :thinking:

### CODE REVIEW

**Comment by tlaferriere** [comment]
Looks like it is using an old version of setuptools. I think I saw version `>=43.x` somewhere in the docs about the `setup.cfg` only support. I don't know if you could update it to something more recent?

**Comment by tomschr** [comment]
Nope. I checked that already and added a little change in `tox.ini` to make sure I have the latest `setuptools`:

```diff
diff --git i/tox.ini w/tox.ini
index 73fbfc5..d6c17df 100644
--- i/tox.ini
+++ w/tox.ini
@@ -95,7 +95,9 @@ basepython = python3
 deps =
     wheel
     twine
+    setuptools >= 43
 commands =
+    # just to make sure we see what's installed:
+    pip list
     python3 setup.py sdist bdist_wheel
     twine check dist/*
```

when I run it

```
$ rm -rf build/ dist/
$ tox -e prepare-dist
[...]
prepare-dist run-test: commands[0] | pip list
[...]
semver             3.0.0.dev2
setuptools         50.3.2    
[...]
prepare-dist run-test: commands[2] | twine check 'dist/*'
Checking dist/semver-3.0.0.dev2-py3-none-any.whl: PASSED
Checking dist/semver-3.0.0.dev2.tar.gz: PASSED
```

As you can see, I have even setuptools version >50. When I extract the `METADATA` from the wheel file, I get:

```
$ cat /tmp/semver3.0.0-dev.2/semver-3.0.0.dev2.dist-info/METADATA
[...]
Summary: attr: semver.__about__.__description__
Home-page: https://github.com/python-semver/python-semver
Author: attr: semver.__about__.__author__
Author-email: attr: semver.__about__.__author_email__
Maintainer: attr: semver.__about__.__maintainer__
Maintainer-email: attr: semver.__about__.__maintainer_email__
[...]
```

Either this is a bug in setuptools or we did something wrong. :smile:

**Comment by tomschr** [comment]
Interesting... after a closer look, the `Version` in the above `METAFILE` has replaced the version from `semver.__about__.__version__` but not the others variables. :thinking:

**Comment by tomschr** [comment]
I think I've found the culprit. According to the table in [Metadata](https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html#metadata) section of the setuptools documentation:


Key | Aliases | Type | Minimum Version | Notes
-- | -- | -- | -- | --
name |   | str |   |  
version |   | attr:, file:, str | 39.2.0 |  
url | home-page | str |   |  
download_url | download-url | str |   |  
project_urls |   | dict | 38.3.0 |  
author |   | str |   |  
author_email | author-email | str |   |  
maintainer |   | str |   |  
maintainer_email | maintainer-email | str |   |  

That means, the `attr:` key is only allowed in version (where it works), but not for `author` and the other keys. Only strings are allowed. :disappointed: 

Seems I need to replace them with the real values.

**Comment by tomschr** [comment]
Success! :tada: After I've updated the fields above, I could upload the files to TestPyPI: https://test.pypi.org/project/semver/3.0.0.dev2/

**Comment by tlaferriere** [comment]
Oh no, such a specific limitation. I wish we could use `attr` in more places. I think I'll go read the issues over in the setuptools repo to see if anyone has suggested this already.

**Comment by tomschr** [comment]
That would be great. 👍I think this is such a nice and elegant feature.
For the moment, it's hard-coded, but if you find a better solution we can always publish a next dev release. 😉

**Pull request merged**
